### ISSUE TITLE
Redundant log info

### ISSUE THREAD

**Issue by KaoImin** [cryptape/cita-bft#101]
## Redundant Details
https://github.com/cryptape/cita-bft/blob/89aae93da815f24ef1150acccab494c0b2cd42d1/src/core/cita_bft.rs#L274

Prevhash, proposer, transactions body, and proof should not appear here. However, the public key should appear here.

---

## Redundant Log
https://github.com/cryptape/cita-bft/blob/795874ce24ed9b6c6f40f0670444267e6d7335e5/src/core/cita_bft.rs#L154:L156

Two info logs are closed to each other, this will influence the performance. Besides the second info is useless because the bft-rs lib will log the received thing.
This case also occurs in the subsequent codes.

**Comment by rev-chaos** [comment]
Thanks for the suggestion. These huge and unreadable prints have replaced by small and readable content.
